source 'https://rubygems.org'

gem 'bcrypt_pbkdf', '~> 1.1.0'
gem 'capistrano', '~> 3.19'
gem 'capistrano-bundler', '~> 2.1'
gem 'capistrano-rails', '~> 1.7'
gem 'capistrano-rvm', '~> 0.1.2'
gem 'capistrano-sidekiq', '~> 3.0'
gem 'capistrano3-puma', '~> 6.0'
gem 'ed25519', '~> 1.3'
gem 'rake'
gem 'rollbar', '~> 3.6'
gem 'whenever', '~> 1.0.0'
