source 'https://rubygems.org'

gem 'bcrypt_pbkdf', '~> 1.1'
gem 'capistrano', '~> 3.20'
gem 'capistrano-bundler', '~> 2.2'
gem 'capistrano-mise', '~> 0.1'
gem 'capistrano-rails', '~> 1.7'
gem 'capistrano-rvm', '~> 0.1.2'
gem 'capistrano-sidekiq', '~> 3.2'
gem 'capistrano3-puma', '~> 8.1'
gem 'ed25519', '~> 1.4'
gem 'rake'
gem 'rollbar', '~> 3.8'
gem 'whenever', '~> 1.1'
